import keymirror from 'keymirror';

export default keymirror({
  SIGNUP_SUCCESSFUL: null,
  SIGNUP_UNSUCCESSFUL: null,
  SIGNUP_VALIDATION_ERROR: null,
  LOG_OUT_SUCCESS: null,
  SIGNIN_SUCCESSFUL: null,
  SIGNIN_UNSUCCESSFUL: null,
  SIGNIN_VALIDATION_ERROR: null,
  CURRENT_USER: null,
  ADD_RECIPE_SUCCESS: null,
  ADD_RECIPE_FAILURE: null,
  IS_RECIPE_CREATING: null,
  GET_USER_RECIPES_SUCCESS: null,
  GET_USER_RECIPES_FAILURE: null,
  VIEW_RECIPE_SUCCESS: null,
  VIEW_RECIPE_FAILURE: null
});